DATASET:
  NAME: "mscoco_common_segm"
  ROOT_TRAIN: "demo_images"
  ROOT_EVAL: "demo_images"
  ROOT_TEST: "demo_images"
  JSON_TRAIN: "demo_images/instances_demo.json"
  JSON_EVAL: "demo_images/instances_demo.json"
  JSON_TEST: "demo_images/instances_demo.json"

DETECTOR:
  NAME: "dcis_res"
  DEPTH: 50
  NUM_CLASS: 80
  NUMDETS: 100
  USE_DCN: False

EVAL:
  CLASS_TH: 0.05
  MASK_TH: 0.5
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0

TEST:
  CLASS_TH: 0.3
  MASK_TH: 0.5
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0

TRAIN:
  LOAD: False
  PRETRAINED: True
  SAVE: False
  FREEZE_BN: True
  FREEZE_STAGES: 1
  MIN_SIZES: [513]
  MAX_SIZE: 1025
  PAD_N: 128
  NUM_EPOCH: 300
  DEVICES: [1]
  BATCH_SIZE: 1
  NUM_WORKERS: 0
  LR_BASE: 0.0005
  LR_GAMMA: 0.1
  LR_SCHEDULE: [60000, 80000]
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  GRAD_CLIP: 10
  WARMUP_ITER: 50
  SEED: 1