DATASET:
  NAME: "mscoco_common_segm"
  ROOT_TRAIN: "/home1/xyt/dataset/coco17/images"
  ROOT_EVAL: "/home1/xyt/dataset/coco17/images"
  ROOT_TEST: "demo_images"
  JSON_TRAIN: "/home1/xyt/dataset/coco17/annotations/instances_train2017.json"
  JSON_EVAL: "/home1/xyt/dataset/coco17/annotations/instances_val2017.json"
  JSON_TEST: "/home1/xyt/dataset/coco17/annotations/instances_val2017.json"

DETECTOR:
  NAME: "scmask_res"
  DEPTH: 50
  NUM_CLASS: 80
  UV_SIZE: 17
  FPN_EXPANDS: [1,2,2,4,8]
  MASK_SIZE: 33
  USE_DCN: false
  SC_CHANNELS: 256

EVAL:
  NMS_TOPK_P: 1000
  NMS_TH: 0.05
  NMS_IOU: 0.6
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0
  MASK_TH: 0.4
  SEG_TH: 0.4
  SIZE_SW: 128

TEST:
  NMS_TOPK_P: 1000
  NMS_TH: 0.5
  NMS_IOU: 0.6
  MIN_SIZE: 513
  MAX_SIZE: 1025
  PAD_N: 128
  DEVICE: 0
  MASK_TH: 0.4
  SEG_TH: 0.4
  SIZE_SW: 128

TRAIN:
  LOAD: False
  SAVE: True
  PRETRAINED: True
  FREEZE_BN: True
  FREEZE_STAGES: 1
  MIN_SIZES: [513]
  MAX_SIZE: 1025
  PAD_N: 128
  NUM_EPOCH: 12
  DEVICES: [1,2,3,4]
  BATCH_SIZE: 16
  NUM_WORKERS: 16
  LR_BASE: 0.01
  LR_GAMMA: 0.1
  LR_SCHEDULE: [60000, 80000]
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  GRAD_CLIP: 10
  WARMUP_ITER: 1000
  SEED: 0
